apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  labels:
    app: chatroulette-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatroulette-back
  template:
    metadata:
      labels:
        app: chatroulette-back
    spec:
      containers:
        - name: back
          image: 810454728139.dkr.ecr.eu-west-3.amazonaws.com/k8-chatroulette-back:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: env-config
          ports:
            - containerPort: 3000
              name: web
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /version
              port: web
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /version
              port: web
              scheme: HTTP
          volumeMounts:
            - mountPath: /images
              name: chat-images
      volumes:
        - name: chat-images

