apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: formation
  labels:
    app: formation-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formation-front
  template:
    metadata:
      labels:
        app: formation-front
    spec:
      containers:
        - name: front
          image: 810454728139.dkr.ecr.eu-west-3.amazonaws.com/formation-k8s-front:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/build/env.js
              name: env-file-for-front
              subPath: env-js
      volumes:
        - name: env-file-for-front
          configMap:
            name: env-file-for-front
