apiVersion: v1
kind: Pod
metadata:
  name: front
  labels:
    app: chatroulette-front
spec:
  containers:
    - name: front
      image: 810454728139.dkr.ecr.eu-west-3.amazonaws.com/k8-chatroulette-front:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          name: web
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /
          port: web
          scheme: HTTP
      livenessProbe:
        httpGet:
          path: /
          port: web
          scheme: HTTP