services:
  back:
    build:
      context: back
    ports:
      - 8080:8080
    environment:
      BDD_PATH: /app/bdd/bdd.json
    volumes:
      - ./bdd:/app/bdd
  front:
    build:
      context: front
    ports:
      - 3000:3000
