apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  labels:
    app: chatroulette-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatroulette-back
  template:
    metadata:
      labels:
        app: chatroulette-back
    spec:
      containers:
        - name: back
          image: 810454728139.dkr.ecr.eu-west-3.amazonaws.com/k8-chatroulette-back:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: web
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /version
              port: web
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /version
              port: web
              scheme: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: back-service
  namespace: formation
  labels:
    app: chatroulette-back
spec:
  selector:
    app: chatroulette-back
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 3000
      protocol: TCP
