apiVersion: v1
kind: Pod
metadata:
  name: back
  namespace: formation
  labels:
    app: formation-back
spec:
  containers:
    - name: back
      image: 810454728139.dkr.ecr.eu-west-3.amazonaws.com/formation-k8s-back:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          name: web
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /
          port: web
          scheme: HTTP
      livenessProbe:
        httpGet:
          path: /
          port: web
          scheme: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: back-service
  namespace: formation
  labels:
    app: formation-back
spec:
  selector:
    app: formation-back
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: formation-lb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          backend:
              service:
                name: back-service
                port:
                  number: 80
          pathType: Prefix
